// GENERATED by scripts/train-risk-model.mjs. Do not edit by hand; re-run `npm run train:model`.
export const RISK_MODEL_WEIGHTS = Object.freeze({
  "id": "ascend-default-lr-v1",
  "trainedAt": "2026-10-09",
  "dataset": {
    "name": "Default of Credit Card Clients (Yeh & Lien, 2009)",
    "source": "OpenML data id 42477",
    "url": "https://www.openml.org/d/42477",
    "licence": "CC0",
    "sha256": "6b621ff9f006c875dcda4ea4163db3574773caa89f06bb36b81973af8062a3f7",
    "rows": 30000,
    "trainingRows": 22312,
    "holdoutRows": 5579,
    "baseRate": 0.2277,
    "excludedColumns": [
      "sex",
      "education",
      "marital status",
      "age"
    ],
    "caveat": "Taiwanese credit-card accounts from 2005. Repayment months stand in for Ascend installments, so estimates are indicative and must be re-fitted on Ascend's own outcomes before production use."
  },
  "seed": 20261009,
  "variants": {
    "history": {
      "intercept": -1.410812,
      "coefficients": {
        "repayments": -0.125867,
        "lateShare": 0.12572,
        "missedShare": 0.522143,
        "anyMissed": 0.432291
      },
      "means": {
        "repayments": 1.858844,
        "lateShare": 0.045538,
        "missedShare": 0.130474,
        "anyMissed": 0.300332
      },
      "scales": {
        "repayments": 0.251716,
        "lateShare": 0.16214,
        "missedShare": 0.255999,
        "anyMissed": 0.458402
      },
      "lambda": 10,
      "metrics": {
        "cvAuc": 0.7381,
        "holdoutAuc": 0.7503,
        "holdoutLogLoss": 0.4491,
        "holdoutBrier": 0.142,
        "holdoutEce": 0.0103,
        "bands": {
          "low": {
            "share": 0.674,
            "defaultRate": 0.114
          },
          "elevated": {
            "share": 0.223,
            "defaultRate": 0.378
          },
          "high": {
            "share": 0.103,
            "defaultRate": 0.649
          }
        }
      },
      "bootstrap95": {
        "repayments": [
          -0.1757,
          -0.0503
        ],
        "lateShare": [
          0.0763,
          0.1854
        ],
        "missedShare": [
          0.4513,
          0.571
        ],
        "anyMissed": [
          0.3796,
          0.4748
        ]
      }
    },
    "history_utilization": {
      "intercept": -1.414647,
      "coefficients": {
        "repayments": -0.160115,
        "lateShare": 0.124125,
        "missedShare": 0.515655,
        "anyMissed": 0.425983,
        "utilization": 0.122738
      },
      "means": {
        "repayments": 1.858844,
        "lateShare": 0.045538,
        "missedShare": 0.130474,
        "anyMissed": 0.300332,
        "utilization": 0.450162
      },
      "scales": {
        "repayments": 0.251716,
        "lateShare": 0.16214,
        "missedShare": 0.255999,
        "anyMissed": 0.458402,
        "utilization": 0.398049
      },
      "lambda": 10,
      "metrics": {
        "cvAuc": 0.7426,
        "holdoutAuc": 0.7561,
        "holdoutLogLoss": 0.4485,
        "holdoutBrier": 0.1418,
        "holdoutEce": 0.0097,
        "bands": {
          "low": {
            "share": 0.706,
            "defaultRate": 0.121
          },
          "elevated": {
            "share": 0.184,
            "defaultRate": 0.387
          },
          "high": {
            "share": 0.11,
            "defaultRate": 0.646
          }
        }
      },
      "bootstrap95": {
        "repayments": [
          -0.2034,
          -0.1097
        ],
        "lateShare": [
          0.0723,
          0.1648
        ],
        "missedShare": [
          0.4502,
          0.5637
        ],
        "anyMissed": [
          0.385,
          0.4933
        ],
        "utilization": [
          0.0902,
          0.168
        ]
      }
    }
  }
});
